openapi: '3.0.2'
info:
  version: '3.0.0'
  title: 'BCMS - REST API'
  description:
    'This is OpenAPI documentation for the BCMS REST API. It is recommended to use
    provided tools (like @becomes/cms-client) for communication with CMS but if you need
    to implement some custom solution this documentation will help you.'
  contact:
    name: 'Becomes'
    url: 'https://thebcms.com/contact'
    email: 'dev@thebcms.com'
servers:
  - url: 'http://localhost:8080/api'
    description: 'Local development'
paths: {}

components:
  schemas:
    BCMSPropType:
      type: string
      enum:
        - STRING
        - NUMBER
        - BOOLEAN
        - DATE
        - ENUMERATION
        - MEDIA
        - GROUP_POINTER
        - ENTRY_POINTER
        - WIDGET
        - RICH_TEXT
    BCMSPropMediaDataParsed:
      type: object
      required:
        - _id
        - security
      properties:
        _id:
          type: string
        src:
          type: string

    BCMSPropDateData:
      type: array
      items:
        type: number
    BCMSPropEnumData:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            type: string
        selected:
          type: string
    BCMSPropEntryPointerData:
      type: object
      required:
        - templateId
        - entryIds
        - displayProp
      properties:
        templateId:
          type: string
        entryIds:
          type: array
          items:
            type: string
        displayProp:
          type: string
    BCMSPropGroupPointerData:
      type: object
      required:
        - _id
      properties:
        _id:
          type: string
    BCMSPropMediaData:
      type: string
    BCMSPropWidgetData:
      type: object
      required:
        - _id
      properties:
        _id:
          type: string
    BCMSPropValue:
      type: object
      required:
        - id
        - data
      properties:
        id:
          type: string
        data:
          $ref: '#/components/schemas/BCMSPropValueData'    
    BCMSPropValueGroupPointerData:
      type: object
      required:
        - _id
        - items
      properties:
        _id:
          type: string
        items:
          type: array
          items:
            type: object
            required:
              - props
            properties:
              props:
                type: array
                items:
                  $ref: '#/components/schemas/BCMSPropValue'
    BCMSPropValueRichTextData:
      type: object
      required:
        - nodes
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryContentNode'
    BCMSPropRichTextData:
      type: object
      required:
        - nodes
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryContentNode'
    BCMSPropValueWidgetData:
      type: object
      required:
        - _id
        - props
      properties:
        _id:
          type: string
        props:
          type: array
          items:
            $ref: '#/components/schemas/BCMSPropValue'
    BCMSPropValueData:
      oneOf:
        - type: array
          items:
            type: string
        - type: array
          items:
            type: boolean
        - type: array
          items:
            type: number
        - $ref: '#/components/schemas/BCMSPropDateData'
        - $ref: '#/components/schemas/BCMSPropValueGroupPointerData'
        - type: array
          items:
            $ref: '#/components/schemas/BCMSPropMediaData'
        - $ref: '#/components/schemas/BCMSPropValueWidgetData'
        - type: array
          items:
            $ref: '#/components/schemas/BCMSPropValueRichTextData'
    BCMSEntryParsedMeta:
      type: object
      additionalProperties:
        x-name: lng
        type: array
        items:
          $ref: '#/components/schemas/BCMSPropParsed'
    BCMSPropEntryPointerDataParsed:
      type: object
      additionalProperties:
        x-name: lng
        type: array
        items:
          $ref: '#/components/schemas/BCMSPropData'
    BCMSPropParsed:
      type: object
      additionalProperties:
        x-name: name
        type: array
        items:
          $ref: '#/components/schemas/BCMSPropDataParsed'
    BCMSPropWidgetDataParsed:
      type: object
      additionalProperties:
        x-name: key
        type: array
        items:
          $ref: '#/components/schemas/BCMSPropDataParsed'
    BCMSPropGroupPointerDataParsed:
      type: object
      additionalProperties:
        x-name: key
        type: array
        items:
          oneOf:
            - $ref: '#/components/schemas/BCMSPropDataParsed'
            - type: array
              items:
                $ref: '#/components/schemas/BCMSPropDataParsed'
    BCMSPropDataParsed:
      oneOf:
        - type: string
        - type: array
          items:
            type: string
        - type: boolean
        - type: array
          items:
            type: boolean
        - type: number
        - type: array
          items:
            type: number
        - $ref: '#/components/schemas/BCMSPropEnumData'
        - $ref: '#/components/schemas/BCMSPropEntryPointerData'
        - $ref: '#/components/schemas/BCMSPropGroupPointerDataParsed'
        - type: array
          items:
            $ref: '#/components/schemas/BCMSPropGroupPointerDataParsed'
        - $ref: '#/components/schemas/BCMSPropWidgetDataParsed'
        - $ref: '#/components/schemas/BCMSPropMediaDataParsed'
        - type: array
          items:
            $ref: '#/components/schemas/BCMSPropMediaDataParsed'
        - type: object
          required:
            - type
            - value
          properties:
            type: 
              $ref: '#/components/schemas/BCMSPropType'
            value:
              $ref: '#/components/schemas/BCMSPropDataParsed'
    BCMSPropData:
      oneOf:
        - type: array
          items:
            type: string
        - type: array
          items:
            type: boolean
        - type: array
          items:
            type: number
        - $ref: '#/components/schemas/BCMSPropDateData'
        - $ref: '#/components/schemas/BCMSPropEnumData'
        - $ref: '#/components/schemas/BCMSPropEntryPointerData'
        - $ref: '#/components/schemas/BCMSPropGroupPointerData'
        - type: array
          items:
            $ref: '#/components/schemas/BCMSPropMediaData'
        - $ref: '#/components/schemas/BCMSPropWidgetData'
        - type: array
          items:
            $ref: '#/components/schemas/BCMSPropRichTextData'
    BCMSProp:
      type: object
      required:
        - id
        - type
        - required
        - name
        - label
        - array
        - defaultData
      properties:
        id:
          type: string
        type:
          $ref: '#/components/schemas/BCMSPropType'
        required:
          type: boolean
        name:
          type: string
        label:
          type: string
        array:
          type: boolean
        defaultData:
          $ref: '#/components/schemas/BCMSPropData'

    BCMSPropChangeUpdate:
      type: object
      required:
        - id
        - label
        - move
        - required
      properties:
        id:
          type: string
        label:
          type: string
        move:
          type: number
        required:
          type: boolean
        enumItems:
          type: array
          items:
            type: string
    BCMSPropChangeAdd:
      type: object
      required:
        - label
        - type
        - required
        - array
      properties:
        label:
          type: string
        type:
          $ref: '#/components/schemas/BCMSPropType'
        required:
          type: boolean
        array:
          type: boolean
        defaultData:
          $ref: '#/components/schemas/BCMSPropData'
    BCMSPropChange:
      type: object
      properties:
        add:
          $ref: '#/components/schemas/BCMSPropChangeAdd'
        remove:
          type: string
        update:
          $ref: '#/components/schemas/BCMSPropChangeUpdate'
    BCMSEntryCreateData:
      type: object
      required:
        - templateId
        - meta
        - content
      properties:
        templateId:
          type: string
        status:
          type: string
        meta:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryMeta'
        content:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryContent'
    BCMSEntryLite:
      type: object
      required:
        - _id
        - createdAt
        - updatedAt
        - cid
        - templateId
        - userId
        - meta
      properties:
        _id:
          type: string
        createdAt:
          type: number
        updatedAt:
          type: number
        cid:
          type: string
        templateId:
          type: string
        userId:
          type: string
        meta:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryMeta'
    BCMSEntryProps:
      type: object
      required:
        - _id
        - createdAt
        - updatedAt
        - cid
        - templateId
        - userId
        - meta
        - content
      properties:
        _id:
          type: string
        createdAt:
          type: number
        updatedAt:
          type: number
        cid:
          type: string
        templateId:
          type: string
        userId:
          type: string
        status:
          type: string
        meta:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryMeta'
        content:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryContent'
    BCMSEntryParsed:
      type: object
      required:
        - _id
        - createdAt
        - updatedAt
        - templateId
        - userId
        - status
        - meta
      properties:
        _id:
          type: string
        createdAt:
          type: number
        updateAt:
          type: number
        templateId:
          type: string
        userId:
          type: string
        status:
          type: string
        meta:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryParsedMeta'
    BCMSEntryUpdateData:
      type: object
      required: 
        - _id
        - templateId
        - meta
        - content
      properties:
        _id:
          type: string
        templateId:
          type: string
        status:
          type: string
        meta:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryMeta'
        content:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryContent'

    BCMSEntryMeta:
      type: object
      required:
        - lng
        - props
      properties:
        lng:
          type: string
        props:
          type: array
          items:
            $ref: '#/components/schemas/BCMSPropValue'

    BCMSEntryContent:
      type: object
      required:
        - lng
        - nodes
      properties:
        lng:
          type: string
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryContentNode'
    BCMSEntryContentNodeHeadingAttr:
      type: object
      required:
        - level
      properties:
        level:
          type: number
    BCMSEntryContentNodeLinkAttr:
      type: object
      required:
        - href
        - target
      properties:
        href:
          type: string
        target:
          type: string
    BCMSEntryContentNodeMarker:
      type: object
      required:
        - type
        - attrs
      properties:
        type:
          $ref: '#/components/schemas/BCMSEntryContentNodeMarkerType'
        attrs:
          $ref: '#/components/schemas/BCMSEntryContentNodeLinkAttr'
    BCMSEntryContentNodeMarkerType:
      type: string
      enum:
        - bold
        - italic
        - underline
        - stripe
        - link
    BCMSEntryContentNodeType:
      type: string
      enum:
        - paragraph
        - heading
        - widget
        - bulletList
        - listItem
        - orderedList
        - text
    BCMSEntryContentNode:
      type: object
      required:
        - type
      properties:
        type:
          $ref: '#/components/schemas/BCMSEntryContentNodeType'
        content:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryContentNode'
        attrs:
          oneOf:
            - $ref: '#/components/schemas/BCMSEntryContentNodeHeadingAttr'
            - $ref: '#/components/schemas/BCMSPropValueWidgetData'
            - $ref: '#/components/schemas/BCMSEntryContentNodeLinkAttr'
        marks:
          type: array
          items:
            $ref: '#/components/schemas/BCMSEntryContentNodeMarker'
        text:
          type: string

    BCMSTemplateCreateData:
      type: object
      required:
        - label
        - desc
        - singleEntry
      properties:
        label:
          type: string
        desc:
          type: string
        singleEntry:
          type: boolean
    BCMSTemplateUpdateData:
      type: object
      required:
        - _id
      properties:
        _id:
          type: string
        label:
          type: string
        desc:
          type: string
        singleEntry:
          type: boolean
        propChanges:
          type: array
          items:
            $ref: '#/components/schemas/BCMSPropChange'
    BCMSTemplateProps:
      type: object
      required:
        - _id
        - createdAt
        - updatedAt
        - cid
        - name
        - label
        - desc
        - userId
        - singleEntry
        - props
      properties:
        _id:
          type: string
        createdAt:
          type: number
        updatedAt:
          type: number
        cid:
          type: string
        name:
          type: string
        label:
          type: string
        desc:
          type: string
        userId:
          type: string
        singleEntry:
          type: boolean
        props:
          type: array
          items:
            $ref: '#/components/schemas/BCMSProp'

  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
    HttpSignature:
      type: http
      scheme: bearer
