version: '3.9'
services:
  backend:
    build: ""
    ports:
      - '1280:1280'
    volumes:
      - type: bind
        source: ./src
        target: /app/src
  shim:
    image: becomes/cms-shim-local
    ports:
      - '1282:1282'
