FROM node:14-slim

WORKDIR /app

COPY . /app

RUN apt update
RUN apt install ffmpeg -y
RUN apt install git -y
RUN apt install curl -y
RUN apt install zip --yes
RUN apt install unzip --yes
RUN mkdir /root/.ssh
RUN ssh-keyscan -H github.com >> /root/.ssh/known_hosts
RUN chmod -R 755 /root/.ssh
RUN npm i

ENTRYPOINT ["npm", "run", "dev"]
