version: '3.9'
services:
  proxy:
    image: 'becomes/cms-proxy-local'
    ports:
      - '8080:8080'
    logging:
      driver: none
  shim:
    depends_on:
      - proxy
    image: 'becomes/cms-shim-local'
    ports:
      - '1282:1282'
  backend:
    depends_on:
      - shim
    build: ''
    ports:
      - '1280:1280'
    volumes:
      - type: bind
        source: ./bcms.config.js
        target: /app/bcms.config.js
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./db
        target: /app/db
      - type: bind
        source: ./uploads
        target: /app/uploads
