version: '3.9'
services:
  proxy:
    image: 'becomes/cms-proxy-local'
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'
    logging:
      driver: none
  shim:
    depends_on:
      - proxy
    image: 'becomes/cms-shim-local'
    ports:
      - '1282:1282'
  backend:
    depends_on:
      - shim
    build: ''
    ports:
      - '1280:1280'
    volumes:
      - type: bind
        source: ./bcms.config.js
        target: /app/bcms.config.js
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./db
        target: /app/db
      - type: bind
        source: ./uploads
        target: /app/uploads
      - type: bind
        source: ./plugins
        target: /app/plugins
#      - type: bind
#        source: /usr/local/lib/node_modules/@becomes/purple-cheetah
#        target: /app/src/node_modules/@becomes/purple-cheetah
