version: '3.9'
networks:
  default:
    external: true
    name: bcms
services:
  backend:
    hostname: 'bcms-backend'
    build:
      context: ''
      dockerfile: Dockerfile.dev
    ports:
      - '1280:1280'
    volumes:
      - type: bind
        source: ./bcms.config.js
        target: /app/bcms.config.js
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./db
        target: /app/db
      - type: bind
        source: ./uploads
        target: /app/uploads
