version: '3.9'
services:
  proxy:
    image: 'becomes/cms-proxy-local:1.0.2'
    ports:
      - '8080:8080'
    logging:
      driver: none
  shim:
    depends_on:
      - proxy
    image: 'becomes/cms-shim-local:1.0.2'
    ports:
      - '1279:1279'
    logging:
      driver: none
  backend:
    depends_on:
      - shim
    build:
      context: '.'
      dockerfile: Dockerfile.dev
    ports:
      - '1280:1280'
    volumes:
      - type: bind
        source: ./bcms.config.js
        target: /app/bcms.config.js
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./db
        target: /app/db
      - type: bind
        source: ./uploads
        target: /app/uploads
      - type: bind
        source: ./_test
        target: /app/_test
