openapi: '3.0.2'
info:
  version: '3.0.0'
  title: 'BCMS Backend - REST API'
  description:
    'This is Swagger documentation for the BCMS REST API. It is recommended to use
    provided tools (like @becomes/cms-client) for communication with CMS but if you need
    to implement some custom solution this documentation will help you.'
  contact:
    name: 'Becomes'
    url: 'https://thebcms.com/contact'
    email: 'dev@thebcms.com'
servers:
  - url: 'http://localhost:@PORT/api'
    description: 'Localhost'
  - url: 'https://cloud.thebcms.com/api/v1/portal/proxy/@ORG_ID/@INSTANCE_ID/api'
    description: 'Localhost'
paths:
  /shim/user/verify/otp:
    post:
      tags:
        - Auth
      responses:
        '200':
          description: OK
